baseURL = "https://cecastillo-1987.github.io/blog-publico/"
languageCode = "es"
title = "Mi Blog"
theme = "twentytwentythree-hugo"
paginate = 10

[params]
  description = "Blog personal usando Hugo y adaptado del tema Twenty Twenty-Three"
  author = "Tu Nombre"

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Acerca de"
    url = "/about/"
    weight = 3
